- _implementors/sdks.md
[LSP4J](https://github.com/eclipse/lsp4j) provides client and server implementations to the Debug Adapter Protocol for JVM.
> Added Eclipse LSP4J to the list of known SDKs

- _implementors/tools.md
[Cloud Studio](https://studio.dev.tencent.com) support DAP for Java
> Add Cloud Studio among the Dev Tools

- _implementors/tools.md
This updates the implementors table to have a link to the Visual Studio Debug Adapter Host repo.
> Add link to Visual Studio Debug Adapter Host repo

- changelog.md
- debugAdapterProtocol.json
- specification.md
Based on Andrew's PR https://github.com/microsoft/vscode-debugadapter-node/pull/212 I've create a new PR for the DAP repo (where the truth lives).
While working on this, I noticed that the new "kind" attribute had a description using the term "hint". This made me think that "presentationHint" would be a better name than "kind" and more in line with the other UI related hints.
Use the "Github Pull Request" extension to conveniently review the changes from with the comfort of your VS Code workspace ;-)
> Support for register access

- _data/specification-toc.yml
- changelog.md
- debugAdapterProtocol.json
- specification.md
Based on Andrew's PR microsoft/vscode-debugadapter-node#212 I've created a new PR for the DAP repo (where the truth lives).
I've only changed the name of the `pointerLength` attribute of the process event to `pointerSize` because the description was already talking about "size" and the Internet thinks that "pointer size" is more common than "pointer length".
> Support for memory access and disassembly

- _implementors/adapters.md
Provides live debugging of Papyrus scripts in Fallout 4 and Skyrim. Distributed along with the language service implementation vscode extension. Thanks!
> Add Papyrus implementation

- debugAdapterProtocol.json
This PR applies the changes described in https://github.com/microsoft/debug-adapter-protocol/issues/62.
After applying the changes to the schema, the TypeScript generator did not produce any changes for the output.
But I expect changes for C# or C++ output of other generators.
@andrewcrawley please review
> change type of references and IDs from "number" to "integer"

- _implementors/adapters.md
myself @ptrthomas and @kirksl are happy to submit [Karate](https://github.com/intuit/karate) to this list, as the developer of the Java server-side I would claim that this is one of the cleanest Java ([Netty](https://netty.io) based) implementations out there, and could be a good reference. here is the source code: [karate/karate-core/src/main/java/com/intuit/karate/debug](https://github.com/intuit/karate/tree/develop/karate-core/src/main/java/com/intuit/karate/debug)
here is a tweet announcing the availability, with a demo video: https://twitter.com/KarateDSL/status/1167533484560142336
we actually support "step-back" and hot-reload of code and are extremely thrilled with what VS Code and the DAP gives us !
> adding karate as a dap implementation

- _data/specification-toc.yml
- debugAdapterProtocol.json
- spec-generator/generator.ts
- specification.md
This allows step requests (Next, StepInto, StepOut, StepBack) to take
an optional 'steppingGranularity', which provides a hint for how far
a debug adapter should let the step go.
This provides support for proposal https://github.com/microsoft/debug-adapter-protocol/issues/110
> Add stepping granularities to the step requests.

- _data/specification-toc.yml
- debugAdapterProtocol.json
- specification.md
This adds support for instruction breakpoints (capability, request,
response, arguments) to the protocol.
This provides support for proposal https://github.com/microsoft/debug-adapter-protocol/issues/102
> Add instruction breakpoints

- _implementors/adapters.md
Add a debug adapter for Kotlin to the list of DAP implementors.
> Add Kotlin Debug Adapter

- _implementors/adapters.md
The Go extension repository has been transferred to github.com/golang/vscode-go.
Updates the information for the debug adapter to reflect the current location and
maintainers.
> Update Go debug extension info in adapters.md

- _implementors/tools.md
https://github.com/mfussenegger/nvim-dap implements DAP for Neovim
> Add nvim-dap to tools page

- debugAdapterProtocol.json
Here is the trivial part of the fix for #122 - but I couldn't get the generated files to rebuild, so I haven't included manually edited versions.
> Bug #122: requestId for ProgressStartEvent is an integer

- debugAdapterProtocol.json
- specification.md
This adds an 'hasDataBreakpoint' attribute and deprecate 'dataBreakpoint' kind at VariablePresentationHint, per #173.
> Add hasDataBreakpoint attribute for VariablePresentationHint

- _implementors/adapters.md
Added a row for the ESP-IDF debug adapter.
Took me a long time to track it down this implementation as a newcomer to VSCode so maybe the link will be helpful for others.
> ESP-IDF debug adapter

- _implementors/adapters.md
This PR updates the debug adapter information for Ballerina by including the new Ballerina extension link.
> Update Ballerina debug adapter information

- _implementors/sdks.md
google/go-dap is the Go implementation of DAP
> Update sdks.md - include go-dap

- debugAdapterProtocol.json
The description of `ExceptionFilterOptions` currently states that it is used in the `setExceptionsFilter`, which does not exist in the specification. 
It is however used in the `setExceptionBreakpoints` request so I assume this is just a wording error, hence the PR.
> Fix a small mistake in `ExceptionFilterOptions`

- css/main.scss
Ref https://github.com/microsoft/debug-adapter-protocol/issues/252
This PR fixes the following trouble spots:
Irregular outline shape around header links on the main page:
Clipped outline around first item of the right nav bar on the Specification page:
> Add padding to some outline elements

- debugAdapterProtocol.json
SetBreakpointsArguments says that either source.path or source.reference must be specified.
However, source does not contain a field named reference .  I think this should say source.sourceReference instead.
(I've checked by making a debug adapter for VS Code, and both "sourceReference" and "path" are used, but not "reference")
> Fix description for SetBreakpointsArguments

- _implementors/adapters.md
[Delve DAP Server](https://github.com/go-delve/delve/tree/master/Documentation/api/dap) is now the official DA for Go.
[VSCode Go extension](https://github.com/golang/vscode-go) no longer maintains its l[egacy DA](https://github.com/golang/vscode-go/tree/master/src/debugAdapter) and offers debugging via [Delve DAP](https://github.com/go-delve/delve/tree/master/Documentation/api/dap).
cc @hyangah @suzmue
> Update adapters.md for Go debug adapter

- _implementors/adapters.md
This PR removes an extra newline in the adapters table which resulted in
the webpage / markdown to incorrectly render the table.
At https://microsoft.github.io/debug-adapter-protocol/implementors/adapters/
> Remove extra newline in adapters.md

- debugAdapterProtocol.json
Closes https://github.com/microsoft/debug-adapter-protocol/issues/291
Specifies hash values as hexadecimal values, which should be unsurprising.
Specifies the timestamp as an [RFC 3339](https://www.rfc-editor.org/rfc/rfc3339). RFC 3339 is the most common profile of ISO 8601, which addresses some shortcomings of the specification (e.g. removing support for two-digit years). Most ISO dates seen in the wild, including those from JavaScript's `new Date().toISOString()`, are RFC 3339 dates.
> specify format of hash and timestamp values

- debugAdapterProtocol.json
Closes https://github.com/microsoft/debug-adapter-protocol/issues/288
> make wording on source.origin more clear to be non-exhaustive

- debugAdapterProtocol.json
Closes https://github.com/microsoft/debug-adapter-protocol/issues/287
Seems like a copy-paste or generation error. The docs for `module` already convey this meaning, so just remove it.
> fix generation kludge in module.path field

- changelog.md
- debugAdapterProtocol.json
> Clarify measurement unit in CompletionsRequest.column

- _implementors/adapters.md
vscode-php-debug was migrated from felixfbecker to xdebug organization and is currently maintained by @zobo
> Update PHP DA information

- changelog.md
- debugAdapterProtocol.json
> Proposal: Allow multiple debug sessions through a single adapter

- debugAdapterProtocol.json
- specification.md
The specification seems to use US English spellings, and in particular "honor" is already used several times, so I've made the spelling consistent.
> Use consistent spelling

- debugAdapterProtocol.json
- specification.md
This PR moves the newly added 'variables' enum for EvaluateArguments context from https://github.com/microsoft/debug-adapter-protocol/commit/87fdf654be233b5c7b0f32aa9a7310c6565e48af to be added at the end instead of at the start of the array.
Reordering the parameters is breaking change for downstream generators.
cc @andrewcrawley
> Move EvaluateArguments context variables to end of enums

- _implementors/sdks.md
I've created a Rust implementation for DAP and released an alpha version on crates.io. It's in a fairly early state (but it's code-complete).
> Update sdks.md - include dap-rs

- changelog.md
- debugAdapterProtocol.json
> clarify the default behavior when kind is omitted from runInTerminal

- debugAdapterProtocol.json
- specification.md
Closes https://github.com/microsoft/debug-adapter-protocol/issues/347
> Clarify that absent canRestart on frame implies true

- _implementors/adapters.md
The Perl Debug project mentioned in the adapters table is currently archived and no longer maintained by the referrenced user. This commit updates the table pointing to the new Perl Debug project url, user and marketplace link.
> Update Perl Debug adapter

- _implementors/tools.md
At the time that `vimspector` was added to the implementors list, it only supported the `vim` editor.  It now also supports the `neovim` `vim` fork as documented at: https://github.com/puremourning/vimspector#dependencies
> Document neovim support by the vimspector implementor

- _data/specification-toc.yml
- changelog.md
- debugAdapterProtocol.json
- specification.md
> add a BreakpointMode for different types of breakpoints

- _implementors/tools.md
Hey!
[dape](https://github.com/svaante/dape) or Debug Adapter Protocol for Emacs is an DAP client that might make a good addition to the list of supported tools.
> Add Emacs dape package to Implementations tools section

- changelog.md
- debugAdapterProtocol.json
- specification.md
A second approach.
Closes #455
> Add `bytes` and `asAddress` properties to the `DataBreakpointInfo` request

- _implementors/adapters.md
The [rebornix Ruby extension](https://github.com/rubyide/vscode-ruby) has been archived by its owner, but debuggging support is available through the Ruby LSP extension.
Closes https://github.com/Shopify/vscode-ruby-lsp/issues/1039
cc @vinistock
> Update adapters list for Ruby LSP

- changelog.md
- debugAdapterProtocol.json
- specification.md
> feat: add a document location to `EvaluateArguments`

- changelog.md
- debugAdapterProtocol.json
- specification.md
> feat: add returnValue as a Scope.presentationHint

- debugAdapterProtocol.json
Following up a comment on #484
> fix: remove single-value wording

- debugAdapterProtocol.json
- specification.md
> fix: clarify of variableReference after setVariable

- _data/specification-toc.yml
- changelog.md
- debugAdapterProtocol.json
- specification.md
Closes https://github.com/microsoft/debug-adapter-protocol/issues/343
> feat: add locations request and references to variable types

- debugAdapterProtocol.json
> Support for ANSI styling in debug output and variables

- changelog.md
- debugAdapterProtocol.json
- specification.md
> fix: clarify how StackTraceArguments.format applies

- _implementors/adapters.md
Midas: A debug adapter using GDB and RR as debugger backends (with a native debugger being in development to replace/add additional backend beyond GDB and interface with RR more closely).
Uses GDB (for now) and makes it more straightforward to start replay session debugging using RR.
> Add Midas to Debug Adapter list, w/ VSCode

- _implementors/adapters.md
It's a debugger using DAP, and it implements most DAP features. Usage field is empty because re-linking the readme seems redundant.
> Add Squirrel Debugger to adapters.md

- changelog.md
- debugAdapterProtocol.json
- overview.md
Fixes #545
Aside from existing discussion, I think this is a good change because
it avoids race conditions if a DA adjusts a breakpoint concurrently
while the client updates those breakpoints (precipitated either via
network latency or just processing latency on either end.)
> fix: clarify representation of breakpoint after changed event

- debugAdapterProtocol.json
Closes https://github.com/microsoft/debug-adapter-protocol/issues/547
> clarify: completion trigger characters

- _implementors/adapters.md
Adds [haskell-debugger](https://well-typed.github.io/haskell-debugger/) to the list.
cc @alt-romes
> Update debug adapters list in adapters.md
