microsoft/debug-adapter-protocol

_implementors/adapters.md
Harbour language is a clipper derivate: https://harbour.github.io/
=> Added harbour language by APerricone

_implementors/tools.md
Theia support DAP since [this PR](https://github.com/theia-ide/theia/pull/2447)
cc @tolusha @slemeur @tsmaeder
=> Add Theia among the Dev Tools

_implementors/adapters.md
=> Add Ballerina debug adapter

_implementors/adapters.md
VDMJ-LSP supports the DAP protocol too.
=> Added VDMJ-LSP to the list of adapters

_implementors/adapters.md
It is a new debugger which is based on transpiling JS/TS code. 
Among the common debugger features it also has programmable API, Time-Traveling, Persistent state, platform independence and more.
=> Effectful JavaScript debugger reference in adapters.md

_implementors/adapters.md
=> Update C/C++ DAP Maintainer

_implementors/tools.md
Add link to JCIDE which implement DAP as  a client.
=> Add link to JCIDE which support DAP

_layouts/default.html, _layouts/specification.html, css/main.scss, index.html
- Add lang=en
- Add missing alt text for carousel images
- Fix aria-controls label to reference existing element
- Tune colors of banner and links
- Tune code block colors
=> Fixes per Accessibility Insights

_implementors/adapters.md, _implementors/sdks.md
* Adapter extension - [VSCode Byebug Debugger](https://marketplace.visualstudio.com/items?itemName=ethan-reesor.vscode-byebug) ([repo](https://gitlab.com/firelizzard/vscode-byebug))
* Adapter - [`byebug-dap` Gem](https://rubygems.org/gems/byebug-dap) ([repo](https://gitlab.com/firelizzard/byebug-dap))
* SDK - [`ruby-dap` Gem](https://rubygems.org/gems/ruby-dap) ([repo](https://gitlab.com/firelizzard/ruby-dap))
=> Add byebug-dap and ruby-dap

debugAdapterProtocol.json, specification.md
Hello,
Here is a small typo fix in the spec.
=> Typo in spec

_implementors/adapters.md
I just added my debugger project to the list.
See https://github.com/maziac/DeZog
=> Added DeZog

_implementors/adapters.md
=> Update VDM DAP server URL

specification.md
=> Add a direct reference to JSON schema

_includes/topnav.html, _layouts/implementors.html, _layouts/specification.html, index.html
=> Fix A11Y issues

_implementors/adapters.md
=> docs(implementors): add OCaml

_implementors/adapters.md
It frontend for [ruby/debug: Debugging functionality for Ruby](https://github.com/ruby/debug)
=> Add `VSCode rdbg Ruby Debugger`

_implementors/tools.md
[OpenSumi](https://github.com/opensumi/core) support DAP
=> Add OpenSumi to the Implementations tools

_implementors/adapters.md
=> Add TLA+ to the list of debug-adapter-protocols

debugAdapterProtocol.json
No change in meaning intended.
=> Fix spelling

changelog.md, debugAdapterProtocol.json
Closes https://github.com/microsoft/debug-adapter-protocol/issues/274
=> add additional properties to StepInTarget

debugAdapterProtocol.json
Closes https://github.com/microsoft/debug-adapter-protocol/issues/286
=> remove unnecessary elaboration in ExceptionInfoResponse

debugAdapterProtocol.json
=> Be consistent about redundant documentation

debugAdapterProtocol.json
=> Consistently use or do not use the word 'must'

specification.md
Generated markdown from the protocol JSON file
=> chore: run spec generator for 1.57

debugAdapterProtocol.json
=> Fix some markup issues (e.g. single quotes to backticks)

index.html, specification.md
=> Documentation generator wasn't run for 1.58

_data/specification-toc.yml, debugAdapterProtocol.json, specification.md
=> Fix minor documentation issues

_data/specification-toc.yml, changelog.md, debugAdapterProtocol.json, specification.md
=> Revert startDebugging changes in specification.md

_data/specification-toc.yml, debugAdapterProtocol.json, spec-generator/generator.ts, specification.md
=> Add startDebugging request

debugAdapterProtocol.json
Fixes https://github.com/microsoft/debug-adapter-protocol/issues/323
=> add a known 'notStopped' error message

changelog.md, debugAdapterProtocol.json, overview.md, specification.md
=> Specification does not define variablesReference lifetime

changelog.md, debugAdapterProtocol.json
Fixes https://github.com/microsoft/debug-adapter-protocol/issues/239
=> clarify eof behavior for readMemory

overview.md
=> Not all integer properties are indicated as such in the spec

debugAdapterProtocol.json
=> Clarify documentation for ErrorResponse Message ids

changelog.md, debugAdapterProtocol.json
=> add an optional frameId to dataBreakpointsInfo

.vscode/settings.json, changelog.md, debugAdapterProtocol.json, specification.md
=> Clarification on setBreakpoints arguments

changelog.md, debugAdapterProtocol.json
=> fix: removed unused ModulesViewDescriptor

changelog.md, debugAdapterProtocol.json
=> fix: clarify applicability of supportsVariablePaging

changelog.md, debugAdapterProtocol.json
Fixes https://github.com/microsoft/debug-adapter-protocol/issues/390
=> Clarify lifetime of DataBreakpoint.dataId

changelog.md
=> Add missing changelog entry

changelog.md, debugAdapterProtocol.json
=> clarify instruction bp offset, add instruction presentationHint

changelog.md, debugAdapterProtocol.json
=> add a breakpoint failure 'reason'

changelog.md, debugAdapterProtocol.json
=> Clarifications for setExceptionBreakpoints

overview.md
=> clarify behavior for unverified breakpoints

changelog.md, overview.md
Closes https://github.com/microsoft/debug-adapter-protocol/issues/459
=> clarify object lifetime in evaluate/output

_data/specification-toc.yml, changelog.md, debugAdapterProtocol.json, specification.md
This reverts commit 406e068718ab22b73b6ea3342d7e276ce0ff6afd.
I want to take a different approach in the upcoming iteration
=> back out DataAddressBreakpointInfo request

_implementors/adapters.md
OpenQASM is assembler language for quantum computers. New of DAP protocol for OpenQASM has been added.
=> Added OpenQASM DAP protocol implementation

debugAdapterProtocol.json, specification.md
Hello! Here is a small typo fix in the spec.
=> Fix typo in BreakpointModeApplicability

_includes/footer.html, css/main.scss
Reverts microsoft/debug-adapter-protocol#477
@connor4312 the change is a website change and thus requires merging into the gh-pages branch.
Edit: actually, does the change require merging into main and then gh-pages?
=> Revert "fix: footer layout"

debugAdapterProtocol.json, specification.md
=> fix: clarify meaning of "system process"

debugAdapterProtocol.json, specification.md
=> fix: inconsistency in "evaluate" description

debugAdapterProtocol.json, specification.md
=> fix: StackFrame.canRestart documentation mismatch

changelog.md, specification.md
Run spec generator and update changelog
=> chore: prep for 1.69

_implementors/adapters.md
Add debug adapter for [Luau](https://luau.org/)
=> chore: add luau debugger

_implementors/tools.md
Hi! I'm the author of ecode and I recently added DAP client support to the code editor.
=> Update tools.md adding a new DAP client: ecode

_implementors/tools.md
Add IntelliJ / LSP4IJ DAP support
=> Add IntelliJ / LSP4IJ DAP support

_implementors/tools.md
Fix markdown table syntax to show LSP4IJ DAP support
=> Fix markdown table syntax to show LSP4IJ DAP support
